 
 
#ifndef HAL_LINEAR_MOTOR_LINEAR_MOTOR_CFG_H_
#define HAL_LINEAR_MOTOR_LINEAR_MOTOR_CFG_H_

#define LINEAR_MOTOR_PORT    PORTD  
#define LINEAR_MOTOR_PIN0    pin0
#define LINEAR_MOTOR_PIN1    pin1


#endif /*  HAL_LINEAR_MOTOR_LINEAR_MOTOR_CFG_H_ */
