


#ifndef HAL_LINEAR_MOTOR_LINEAR_MOTOR_INTERFACING_H_
#define HAL_LINEAR_MOTOR_LINEAR_MOTOR_INTERFACING_H_

void LINEAR_MOTOR_Init();

void LINEAR_MOTOR_Extend();

void LINEAR_MOTOR_Retract();



#endif /* HAL_LINEAR_MOTOR_LINEAR_MOTOR_INTERFACING_H_ */
