 
 
#ifndef HAL_SEEDING_MOTOR_SEEDING_MOTOR_CFG_H_
#define HAL_SEEDING_MOTOR_SEEDING_MOTOR_CFG_H_

#define SEEDING_MOTOR1_PORT    PORTB  
#define SEEDING_MOTOR1_PIN0    pin0
#define SEEDING_MOTOR1_PIN1    pin1
#define SEEDING_MOTOR2_PORT    PORTB  
#define SEEDING_MOTOR2_PIN2    pin2
#define SEEDING_MOTOR2_PIN3    pin3

#endif 
