/*
 * TIMER1_cfg.h
 *
 *  Created on: Jul 28, 2022
 *      Author: Karim
 */

#ifndef MCAL_TIMERS_TIMER1_CFG_H_
#define MCAL_TIMERS_TIMER1_CFG_H_


#define TIMER1_ENABLE       ENABLE

/* Options
 * TIMER_OVF
 * TIMER1_PHASECORRECT_OCR1A
 * TIMER1_FASTPWM_OCR1A
 * TIMER1_CTC_OCR1A
 * TIMER1_CTC_ICR1
 * TIMER1_PHASECORRECT_ICR1
 * TIMER1_FASTPWM_ICR1
 * TIMER1_PHASECORRECT_8_BITS
 * TIMER1_PHASECORRECT_9_BITS
 * TIMER1_PHASECORRECT_10_BITS
 * TIMER1_PHASE_FREQ_CORRECT_OCR1A
 * TIMER1_PHASE_FREQ_CORRECT_ICR1
 * TIMER1_FASTPWM_8_BITS
 * TIMER1_FASTPWM_9_BITS
 * TIMER1_FASTPWM_10_BITS
 */
#define    TIMER1_MODE       TIMER_OVF


/* Options
 * NORMAL_MODE_OC1A
 * NORMAL_MODE_OC1B
 * TOGGLE_OC1A
 * NON_INVERTING_OC1A
 * INVERTING_OC1A
 * TOGGLE_OC1B
 * NON_INVERTING_OC1B
 * INVERTING_OC1B
 */
#define 	TIMER1A_COMPARE_MATCH_OP_MODE       TOGGLE_OC1A
#define 	TIMER1B_COMPARE_MATCH_OP_MODE       TOGGLE_OC1B


/* Options
 * ENABLE
 * DISABLE
 */
#define TIMER1_OVF_INTERRUPT_ENABLE      DISABLE
#define TIMER1_CTC_INTERRUPT_ENABLE      ENABLE
/* Options
 * 1- NOPRESCALING
 * 2- TIMER1_PS_8
 * 3- TIMER1_PS_64
 * 4- TIMER1_PS_256
 * 5- TIMER1_PS_1024
 * 6- EX_CLK_FALLING_EDGE
 * 7- EX_CLK_FALLING_EDGE
 */
#define TIMER1_PRESCALER                  TIMER1_PS_8
/* Options for 50 HZ
 * 156 for 1024 prs
 * 625  for 256 prs
 * 2500   for 64 prs
 * 20000    for 8 prs
 */
#define TOP   625


#endif /* MCAL_TIMERS_TIMER1_CFG_H_ */
